name: Get Version

on:
  push:
    branches: 
    - 'integration'
    - 'feature/**'

jobs:  
  setVersion: 
    name: Bump version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: main, integration, feature/* 
        DEFAULT_BUMP: patch
        WITH_V: false
  
  branchName: 
    name: get branch name
    runs-on: ubuntu-latest
    steps:
      - id: get_branchName
        uses: battila7/get-version-action@v2     
      - run: echo ${{ steps.get_version.outputs.version-without-v }}
