name: NPM - Release

on:
  push:
    branches: [main,integration,feature/**]
  pull_request:
    branches: [main,integration,feature/**]

env:
  Branches: main,integration,feature/**
  MainBranch: main
  NPMRegistry: https://registry.npmjs.org/
  InstallCommand: npm ci
  DeployCommand: npm run deploy
  Organization: lowcodeunit
  Repository: applications-flow
  Output: dist
